"use client";
import { useEffect, useState } from "react";
import { asset } from "./asset";
type Clue="cave"|"fire"|"tools"|"mammoth"; type Answer="strength"|"cooperation"|"magic"|null;
type Progress={page:number;highestPage:number;dialTurned:boolean;foundClues:Clue[];quizAnswer:Answer};
const initial:Progress={page:1,highestPage:1,dialTurned:false,foundClues:[],quizAnswer:null};
const storageKey="historia-en-casa-progress-v1";
const clueData:{id:Clue;label:string;text:string;className:string}[]=[
 {id:"cave",label:"Cueva",text:"Arte y señales: conservan ideas, aunque no siempre sabemos con certeza qué significaban.",className:"hot-cave"},
 {id:"fire",label:"Fuego",text:"Calor, luz, protección y cocina. Mantenerlo requería atención y cooperación.",className:"hot-fire"},
 {id:"tools",label:"Herramientas",text:"Piedra, madera y hueso se convertían en tecnología: conocimiento aplicado.",className:"hot-tools"},
 {id:"mammoth",label:"Mamut",text:"Humanos y grandes animales convivieron en paisajes fríos y cambiantes.",className:"hot-mammoth"}
];
const activities=[
 {title:"Una pared que cuenta",meta:"5–8 años · interior · 35 min",goal:"Comunicar una idea sin escritura y observar formas animales.",materials:"Papel kraft, café o té frío, témpera infantil ocre, roja y negra, esponja y dedos.",steps:["Envejeced el papel con café o té y dejadlo secar.","Elegid un animal o una idea que queráis contar.","Pintad con dedos y esponja; luego interpretad las imágenes."],voice:"Samara pregunta: «¿Qué pistas ayudan a entender el dibujo?»",safety:"No tocar ni pintar cuevas o abrigos reales."},
 {title:"Un lugar contra el viento",meta:"6–9 años · exterior · 60 min",goal:"Probar estructuras, repartir tareas y mejorar un diseño.",materials:"Ramas caídas y ligeras, cuerda gruesa, sábana vieja y pinzas grandes.",steps:["Buscad un lugar llano y repartid tareas.","Montad una estructura baja con ayuda adulta.","Probad de qué lado entra el viento y mejorad el refugio."],voice:"Julia propone: «¡Probemos una mejora cada vez!»",safety:"Supervisión adulta; no trepar; comprobar estabilidad y entorno."},
 {title:"Una forma para una función",meta:"6–10 años · interior o exterior · 45 min",goal:"Partir de un problema para diseñar una herramienta.",materials:"Palo sin astillas, arcilla o piedra roma, lana o cordón y cartón.",steps:["Elegid un problema: alcanzar, transportar o marcar.","Dibujad una herramienta y explicad cada parte.","Construid un modelo sin filo y comprobad su forma."],voice:"Lucas pregunta: «¿Y si el primer diseño no funciona?»",safety:"No tallar piedra, crear filos ni dejar golpes reales a los niños."}
];
const years=[
 ["Los orígenes","Primeros humanos","Vida nómada","Agricultores","Aldeas"],
 ["Grandes civilizaciones","Mesopotamia","Egipto","Grecia","Roma"],
 ["Civilizaciones del mundo","China","Mesoamérica","Andes","Norteamérica"],
 ["Edad Media","Al-Ándalus","Vikingos","Castillos","Monasterios"],
 ["Edad Moderna","Renacimiento","Dos mundos","Siglo XVII","Ciencia"],
 ["Mundo contemporáneo","Industria","Campo y ciudad","Nuestros abuelos","El futuro"]
];
function validate(raw:unknown):Progress{if(!raw||typeof raw!=="object")return initial;const x=raw as Partial<Progress>,allowed:Clue[]=["cave","fire","tools","mammoth"],answers:Answer[]=["strength","cooperation","magic",null];return{page:Math.min(4,Math.max(1,Number.isInteger(x.page)?x.page!:1)),highestPage:Math.min(4,Math.max(1,Number.isInteger(x.highestPage)?x.highestPage!:1)),dialTurned:x.dialTurned===true,foundClues:Array.isArray(x.foundClues)?[...new Set(x.foundClues.filter((v):v is Clue=>allowed.includes(v as Clue)))]:[],quizAnswer:answers.includes(x.quizAnswer as Answer)?x.quizAnswer as Answer:null}}
export default function StoryExperience(){
 const [progress,setProgress]=useState(initial),[ready,setReady]=useState(false),[activity,setActivity]=useState(0),[selected,setSelected]=useState<string[]>([]);
 // La hidratación del estado persistido solo puede hacerse en el cliente.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{try{setProgress(validate(JSON.parse(localStorage.getItem(storageKey)||"null")))}catch{setProgress(initial)}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(storageKey,JSON.stringify(progress))}catch{}},[progress,ready]);
 const go=(page:number)=>setProgress(p=>({...p,page,highestPage:Math.max(p.highestPage,page)}));
 const reset=()=>{try{localStorage.removeItem(storageKey)}catch{}setProgress(initial)};
 const find=(id:Clue)=>setProgress(p=>({...p,foundClues:p.foundClues.includes(id)?p.foundClues:[...p.foundClues,id]}));
 const toggle=(item:string)=>setSelected(s=>s.includes(item)?s.filter(x=>x!==item):s.length<3?[...s,item]:s);
 return <>
 <section className="section story-section" id="cuento"><div className="section-heading"><span className="eyebrow">Capítulo 1 · La llama compartida</span><h2>Un cuento que se abre con tus descubrimientos</h2></div><div className="story-shell">
 <nav className="steps" aria-label="Páginas del cuento">{["El hallazgo","La aguja","El campamento","La pregunta"].map((n,i)=><button key={n} onClick={()=>go(i+1)} disabled={progress.highestPage<i+1} aria-current={progress.page===i+1?"step":undefined}><span>{i+1}</span>{n}</button>)}</nav>
 <article className="story-page" aria-live="polite">
 {progress.page===1&&<><p className="page-count">Página 1 de 4</p><h3>El hallazgo</h3><p>Lucas apartó hojas junto a una roca rojiza. Parecía enorme, pero era demasiado ligera. Debajo esperaba una caja de madera.</p><blockquote>—¿Por qué la esconderían? —preguntó Samara.<br/>—¡Vamos a abrirla! —dijo Julia.<br/>—¿Y si no sabemos qué hay dentro? —susurró Lucas.</blockquote><p>La tapa crujió. Dentro había un reloj de latón… sin una sola hora.</p><button className="button" onClick={()=>go(2)}>Abrir la caja</button></>}
 {progress.page===2&&<><p className="page-count">Página 2 de 4</p><h3>La aguja</h3><p>En vez de números, el dial tenía marcas como caminos. Los tres apoyaron una mano.</p><button className={`dial ${progress.dialTurned?"turned":""}`} aria-label="Girar la aguja del reloj" onClick={()=>setProgress(p=>({...p,dialTurned:true}))}><span className="needle"/><span>{progress.dialTurned?"Hace unos 35.000 años":"Girar la aguja"}</span></button>{progress.dialTurned&&<button className="button" onClick={()=>go(3)}>Entrar en el campamento</button>}</>}
 {progress.page===3&&<><p className="page-count">Página 3 de 4</p><h3>El campamento</h3><p>El aire olía a humo y nieve. Encuentra las cuatro pistas.</p><div className="scene"><img src={asset("prehistoric-fire-scene.png")} alt="Campamento paleolítico con cueva, fuego compartido, herramientas y mamuts"/>{clueData.map(c=><button key={c.id} className={`hotspot ${c.className} ${progress.foundClues.includes(c.id)?"found":""}`} aria-pressed={progress.foundClues.includes(c.id)} aria-label={`Explorar ${c.label}`} onClick={()=>find(c.id)}>{progress.foundClues.includes(c.id)?"✓":"+"}</button>)}</div><p className="status" role="status">{progress.foundClues.length} de 4 pistas encontradas</p><div className="clue-notes">{clueData.filter(c=>progress.foundClues.includes(c.id)).map(c=><p key={c.id}><strong>{c.label}:</strong> {c.text}</p>)}</div><button className="button" disabled={progress.foundClues.length<4} onClick={()=>go(4)}>Sentarse junto al fuego</button></>}
 {progress.page===4&&<><p className="page-count">Página 4 de 4</p><h3>La pregunta</h3><p>Alrededor de la llama, cada persona aportaba algo. Las herramientas no eran solo objetos: eran conocimientos observados, probados, enseñados y mejorados por muchas manos.</p><fieldset className="quiz"><legend>¿Qué ayudó más al grupo a vivir y aprender?</legend>{[["strength","La fuerza de una sola persona"],["cooperation","Observar, aprender y cooperar"],["magic","La magia de un reloj"]].map(([v,l])=><label key={v}><input type="radio" name="quiz" checked={progress.quizAnswer===v} onChange={()=>setProgress(p=>({...p,quizAnswer:v as Answer}))}/>{l}</label>)}</fieldset>{progress.quizAnswer&&<p className="feedback" role="status">{progress.quizAnswer==="cooperation"?"Exacto: compartir experiencia permitió resolver más problemas juntos.":"Vuelve a mirar las pistas: ¿qué podía transmitirse y mejorar entre personas?"}</p>}<a className={`button ${progress.quizAnswer!=="cooperation"?"disabled-link":""}`} aria-disabled={progress.quizAnswer!=="cooperation"} tabIndex={progress.quizAnswer==="cooperation"?0:-1} href="#actividades">Llevar la historia a casa</a></>}
 </article><button className="reset" onClick={reset}>Empezar de nuevo</button></div></section>
 <section className="section green" id="actividades"><div className="section-heading"><span className="eyebrow">Hacer en familia</span><h2>Tres misiones seguras</h2></div><div className="tabs" role="tablist" aria-label="Actividades">{activities.map((a,i)=><button role="tab" aria-selected={activity===i} aria-controls="activity-panel" id={`tab-${i}`} key={a.title} onClick={()=>setActivity(i)}>{a.title}</button>)}</div><article className="activity" role="tabpanel" id="activity-panel" aria-labelledby={`tab-${activity}`}><p className="meta">{activities[activity].meta}</p><h3>{activities[activity].title}</h3><div className="activity-grid"><div><h4>Objetivo</h4><p>{activities[activity].goal}</p><h4>Materiales</h4><p>{activities[activity].materials}</p></div><div><h4>Pasos</h4><ol>{activities[activity].steps.map(s=><li key={s}>{s}</li>)}</ol></div></div><blockquote>{activities[activity].voice}</blockquote><aside className="safety"><strong>Para hacerlo con seguridad:</strong> {activities[activity].safety}</aside></article></section>
 <section className="section" id="reto"><div className="challenge"><div><span className="eyebrow">Reto de ingenio</span><h2>Solo puedes llevar tres cosas</h2><p>Pasarás una noche en el bosque antiguo. No hay una única combinación correcta.</p></div><div className="object-list">{["Agua","Manta","Olla metálica","Móvil sin cobertura","Bolsa de caramelos","Juguete gigante"].map(item=><button key={item} aria-pressed={selected.includes(item)} disabled={!selected.includes(item)&&selected.length>=3} onClick={()=>toggle(item)}>{selected.includes(item)?"✓ ":""}{item}</button>)}<p className="status" role="status">{selected.length}/3 elegidos{selected.length?`: ${selected.join(", ")}`:""}</p>{selected.length===3&&<p className="prompt">¿Para qué sirve cada objeto? ¿Qué problema sigue sin resolverse?</p>}</div></div></section>
 <section className="section map-section" id="mapa"><div className="section-heading"><span className="eyebrow">6 años · 24 estaciones</span><h2>El mapa de todos los viajes</h2></div><div className="years">{years.map((y,i)=><article className="year card" key={y[0]}><p className="meta">Año {i+1} {i===0&&<span className="here">Estamos aquí</span>}</p><h3>{y[0]}</h3><ol>{y.slice(1).map((s,j)=><li key={s}><span>{j+1}</span>{s}</li>)}</ol></article>)}</div></section>
 <section className="section guide" id="guia"><div><span className="eyebrow">Guía para adultos</span><h2>Leer, hacer y conversar</h2><p>Leed por turnos, dejad que las preguntas respiren y pedid razones. La meta no es memorizar fechas, sino observar necesidades, cooperación y cambios tecnológicos.</p><h3>Una historia contada con cautela</h3><p>Situamos el viaje hace unos 35.000 años, sin asegurar significados desconocidos de signos o pinturas. Tecnología significa conocimiento aplicado. No incluimos pan: sus evidencias conocidas son mucho más recientes, de hace unos 14.400 años.</p></div><aside><h3>Fuentes para seguir explorando</h3><ul><li><a href="https://humanorigins.si.edu/human-characteristics/humans-change-world" target="_blank" rel="noreferrer">Smithsonian — hogares y refugios</a></li><li><a href="https://humanorigins.si.edu/evidence/behavior/stone-tools" target="_blank" rel="noreferrer">Smithsonian — herramientas de piedra</a></li><li><a href="https://whc.unesco.org/en/list/310/" target="_blank" rel="noreferrer">UNESCO — Altamira y arte paleolítico</a></li></ul><p className="safety"><strong>Seguridad:</strong> los modelos infantiles nunca reproducen filos, golpes ni fuego real.</p></aside></section>
 </>;
}
